// ─── Existing ────────────────────────────────────────────────────────────────
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const CHARGING_STATION_REPOSITORY = 'CHARGING_STATION_REPOSITORY';
export const TARIFF_REPOSITORY = 'TARIFF_REPOSITORY';

// ─── New ─────────────────────────────────────────────────────────────────────
export const VEHICLE_REPOSITORY = 'VEHICLE_REPOSITORY';
export const DRIVER_REPOSITORY = 'DRIVER_REPOSITORY';
export const CHARGING_TERMINAL_REPOSITORY = 'CHARGING_TERMINAL_REPOSITORY';
export const FLEET_ACCOUNT_REPOSITORY = 'FLEET_ACCOUNT_REPOSITORY';
export const CHARGING_SESSION_REPOSITORY = 'CHARGING_SESSION_REPOSITORY';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const BOOKING_REPOSITORY = 'BOOKING_REPOSITORY';
export const SUPPORT_TICKET_REPOSITORY = 'SUPPORT_TICKET_REPOSITORY';
export const ALERT_REPOSITORY = 'ALERT_REPOSITORY';
