export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const CHARGING_STATION_REPOSITORY = 'CHARGING_STATION_REPOSITORY';
export const FRANCHISE_DETAILS_REPOSITORY = 'FRANCHISE_DETAILS_REPOSITORY';
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY';
export const TARIFF_REPOSITORY = 'TARIFF_REPOSITORY';
export const TAX_REPOSITORY = 'TAX_REPOSITORY';
